Microverse trail self-review project
fatima-najafi/Microverse-trail-self-review pull request #1
Opened 2023-05-02 12:41 UTC by fatima-najafi

In this project I follows these steps:
- Create a new empty repo.

- Create a new branch for this project
- Open a pull request.
- Play the role of the Code Reviewer:
- Follow the list from the article 
- Check if you have used semantic HTML tags (see examples of these tags in the first bullet of the best practices document below).
- Check if you applied [HTML & CSS best practices

2023-05-02 12:54 UTC, fatima-najafi commented on .github/workflows/linters.yml
> +          node-version: "18.x"
- In this project i checked these steps:
- Does the reviewed project run on your machine?
- Does the reviewed project work properly?
- Are there any [linters errors](https://github.com/microverseinc/linters-config)?
- Is the correct flow used?
- Is the repository [documented in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)?
- Are there any bugs that were missed by the author?

2023-05-02 12:58 UTC, fatima-najafi commented on style.css
> +  display: flex;
I used Use semantic HTML tags. And also add some new features about HTML and CSS such as flex box.

2023-05-02 13:05 UTC, fatima-najafi reviewed
good work and  I follow those step that mentioned in code reviewer.

2023-05-02 13:40 UTC, Gambit142 commented on style.css
> +  display: flex;
- [ ] Please, use the inline comments to pick out codes that were written wrongly. When writing comments using the inline comments feature, you should ensure that the comment is polite, explains the reason why the code written is not good and it should be easy to understand. Take a look at the following comments:

#### Example of Polite comments 
 
> **_Kindly_** use Stylelint linters for this project. 
> I think it would be better to use Stylelint linters for this project. 

#### Example of a clear and easy-to-understand comment

 > **_Kindly_** use Stylelint linters for this project. Stylelint reports bad codes in your CSS files. It helps to enforce consistent code and prevents you from making errors in your stylesheets. 👍 😎 
 
 #### Example of a well-explained request
 
> Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible

2023-05-02 14:14 UTC, fatima-najafi commented on index.html
> +    <div class="main-content">
It sounds good to use Semantic tag because Semantic HTML is the use of HTML markup to reinforce the semantics, or meaning, of the information in web pages and web applications rather than merely to define its presentation or look. Semantic HTML is processed by traditional web browsers as well as by many other user agents.

2023-05-03 08:37 UTC, AlphaNtihinduka requested changes
## Hi @fatima-najafi 🙋‍♂️
Good job working on implementing the changes required by the previous reviewer. You have done the design to do the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is not yet professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- _Kindly consider the inline comments._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-05-03 08:37 UTC, AlphaNtihinduka commented on index.html
> +    <div class="main-content">
- [ ] You did great to ensure that the reason is provided. But however, you did not specify which changes are required. You should define the problem, what you need to be changed and explain why the changes should be important. Kindly be specific about what should be changed for semantic reasons ☺️.

Note: Kindly consider using the `editing` feature to update your comment.

2023-05-04 16:57 UTC, V-Blaze approved these changes
Hi @fatima-najafi  

# Approved 🍏 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![green-lantern-ok](https://user-images.githubusercontent.com/107632780/229644347-63cd2692-a569-4093-9c95-9fad40e2d9f2.gif)

## Highlights
- Used GitHub inline comment feature✔✔
- Gave reasons for the suggested changes :heavy_check_mark: :+1: 

## Optional suggestions

- [OPTIONAL] When performing reviews in subsequent milestones, I'll suggest you use a couple of emojis and/or gifs in the review, they make the code review more human-friendly. :smile: :wave: :+1: 


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 17:23 UTC, merged